import Head from 'next/head';
// import Loading from 'react-content-loader';
import Slider from '../components/molecules/slider';
import Category from '../components/molecules/category';

import styles from '../styles/Home.module.css';

function Home() {
   return (
      <div className={styles.section}>
         <Head>
            <title>Negozio - Landing Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/negozio.svg" />
         </Head>
         <Slider />
         <Category />
      </div>
   );
}

export default Home;
